Added steps to attach and mount Block Storage

diff --git a/.github/workflows/render-tiles.yml b/.github/workflows/render-tiles.yml
--- a/.github/workflows/render-tiles.yml
+++ b/.github/workflows/render-tiles.yml
@@ -1,6 +1,12 @@
 name: Render Tiles
 
-on: workflow_dispatch
+on: 
+  workflow_dispatch:
+    inputs:
+      disable-cleanup-job:
+        description: 'Disable the Cleanup job'
+        default: 'false'
+        required: false
 
 jobs:
   render-tiles:
@@ -10,17 +16,14 @@ jobs:
     env:
       IMAGE_TAG: ${{ github.sha }}
     steps:
-      - name: Store the SSH private key for Digital Ocean
-        run: |
-          echo "${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}" > ${{ runner.temp }}/id_rsa
-          chmod 600 ${{ runner.temp }}/id_rsa
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Configure SSH
-        run: |
-          mkdir -p ~/.ssh
-          echo "StrictHostKeyChecking=no" >> ~/.ssh/config
-          chmod 600 ~/.ssh/config
-      
+        uses: ./.github/actions/configure-ssh
+        with:
+          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
+
       - name: Install doctl
         uses: digitalocean/action-doctl@v2
         with:
@@ -42,7 +45,9 @@ jobs:
               --wait \
               tiles-$IMAGE_TAG \
             )
+            DROPLET_IP=$(doctl compute droplet get $DROPLET_ID --no-header --format=PublicIPv4)
             echo "DROPLET_ID=$DROPLET_ID" >> $GITHUB_ENV
+            echo "DROPLET_IP=$DROPLET_IP" >> $GITHUB_ENV
 
       - name: Assign the droplet to the project
         run: |
@@ -51,18 +56,128 @@ jobs:
             ${{ secrets.DIGITAL_OCEAN_PROJECT_ID_TILES }} \
             --resource=do:droplet:${{ env.DROPLET_ID}}
 
-      - name: Poll for SSH connectivity
+      - name: Poll for SSH connectivity to the Droplet
         run: |
-          MAX_RETRIES=5
+          MAX_RETRIES=3
           SLEEP_TIME=10
-          for i in $(seq 1 $MAX_RETRIES); do doctl compute ssh ${{ env.DROPLET_ID}} --ssh-key-path ${{ runner.temp }}/id_rsa && break || sleep $SLEEP_TIME; done
+          sleep $SLEEP_TIME  # Sleep before the first attempt
+          for i in $(seq 1 $MAX_RETRIES); do
+            doctl compute ssh ${{ env.DROPLET_ID}} --ssh-key-path ${{ runner.temp }}/id_rsa && break
+            sleep $SLEEP_TIME  # Sleep between retries
+          done
+
+      - name: Attach the re-usable Block Storage volume to the Droplet
+        run: |
+          BLOCK_STORAGE_VOLUMES=$(doctl compute volume list --format "ID,Name,DropletIDs" --no-header)
+          BLOCK_STORAGE_VOLUME_ID=""
+          BLOCK_STORAGE_ATTACHED_DROPLET_ID=""
+          while IFS= read -r line; do
+            volume_id=$(echo "$line" | awk '{print $1}')
+            volume_name=$(echo "$line" | awk '{print $2}')
+            attached_droplet_id=$(echo "$line" | awk '{print $3}')
+            if [[ "$volume_name" == "${{ vars.BLOCK_STORAGE_VOLUME_NAME }}" ]]; then
+              BLOCK_STORAGE_VOLUME_ID=$volume_id
+              BLOCK_STORAGE_ATTACHED_DROPLET_ID=$attached_droplet_id
+              echo $BLOCK_STORAGE_ATTACHED_DROPLET_ID
+              break
+            fi
+          done <<< "$BLOCK_STORAGE_VOLUMES"
+          if [[ ! -z "$BLOCK_STORAGE_ATTACHED_DROPLET_ID" ]]; then
+            echo "Block Storage volume is already attached to another Droplet: $BLOCK_STORAGE_ATTACHED_DROPLET_ID"
+            exit 1
+          elif [[ -z "$BLOCK_STORAGE_VOLUME_ID" ]]; then
+            echo "Creating Block Storage volume"
+            BLOCK_STORAGE_VOLUME_ID=$(doctl compute volume create ${{ vars.BLOCK_STORAGE_VOLUME_NAME }} --region ${{ vars.DIGITAL_OCEAN_REGION }} --size ${{ vars.BLOCK_STORAGE_VOLUME_SIZE }} --fs-type ext4 --format ID --no-header)
+            echo "Created Block Storage volume: $BLOCK_STORAGE_VOLUME_ID"
+          fi
+          echo "Attaching the Block Storage volume to the Droplet"
+          doctl compute volume-action attach $BLOCK_STORAGE_VOLUME_ID ${{ env.DROPLET_ID }} --wait
+          echo "BLOCK_STORAGE_VOLUME_ID=$BLOCK_STORAGE_VOLUME_ID" >> $GITHUB_ENV
+
+      - name: Verify that Block Storage is mounted within the Droplet
+        run: |
+          doctl compute ssh ${{ env.DROPLET_ID }} --ssh-key-path ${{ runner.temp }}/id_rsa --ssh-command "set -e; bash -s" <<EOF
+          EXPECTED_BLOCK_STORAGE_DEVICE_PATH="/dev/disk/by-id/scsi-0DO_Volume_${{ vars.BLOCK_STORAGE_VOLUME_NAME }}"
+          EXPECTED_MOUNT_POINT="/mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }}"
+
+          echo "Checking block storage device is attached with the expected device path..."
+          if [ ! -z "\$(lsblk -no MOUNTPOINT $EXPECTED_BLOCK_STORAGE_DEVICE_PATH)" ]; then
+            echo "Block Storage device is attached to the droplet at \$EXPECTED_BLOCK_STORAGE_DEVICE_PATH"
+          else
+            echo "Error: Block Storage device is not properly attached to the Droplet at: \$EXPECTED_BLOCK_STORAGE_DEVICE_PATH"
+            exit 1
+          fi
+
+          echo "Checking mount point..."
+          if ! mount | grep -q \$EXPECTED_MOUNT_POINT; then
+            echo "Mounting the Block Storage volume within the Droplet"
+            mkdir -p /mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }}
+            mount -o discard,defaults,noatime -t ext4 \$EXPECTED_BLOCK_STORAGE_DEVICE_PATH /mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }}
+          fi
+
+          MOUNTED_DEVICE_PATH=\$(mount | grep \$EXPECTED_MOUNT_POINT | cut -d' ' -f1)
+          echo "- Mounted device path: \$MOUNTED_DEVICE_PATH"
+          DEVICE_PATH_CANONICAL=\$(readlink -f \$MOUNTED_DEVICE_PATH)
+          echo "- Actual canonical device path: \$DEVICE_PATH_CANONICAL"
+          EXPECTED_DEVICE_PATH_CANONICAL=\$(readlink -f \$MOUNTED_DEVICE_PATH)
+          echo "- Expected canonical device path: \$EXPECTED_DEVICE_PATH_CANONICAL"
+
+          if [ -z "\$DEVICE_PATH_CANONICAL" ] || [ -z "\$EXPECTED_DEVICE_PATH_CANONICAL" ]; then
+            echo "Failed to resolve one or both of the device paths"
+            exit 1
+          elif [ "\$DEVICE_PATH_CANONICAL" != "\$EXPECTED_DEVICE_PATH_CANONICAL" ]; then
+            echo "An unexpected device (\$MOUNTED_DEVICE_PATH) is mounted at \$EXPECTED_MOUNT_POINT"
+            exit 1
+          else
+            echo "The device \$MOUNTED_DEVICE_PATH is mounted at \$EXPECTED_MOUNT_POINT"
+          fi
+
+          ls -la \$EXPECTED_MOUNT_POINT
+          df -h \$EXPECTED_MOUNT_POINT
+          EOF
 
       - name: Run SSH script
         run: |
           doctl compute ssh ${{ env.DROPLET_ID}} --ssh-key-path ${{ runner.temp }}/id_rsa --ssh-command "set -e; bash -s" <<EOF
-          touch ${{ env.IMAGE_TAG }}_${{ github.run_number }}
+          ls /mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }}/
+          touch /mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }}/${{ env.IMAGE_TAG }}_${{ github.run_number }}
           EOF
 
-      - name: Destroy the Droplet
+
+  cleanup:
+    name: Cleanup
+    needs: [prepare-droplet, download-osm-data, merge-osm-data-files, render-tiles]
+    if: (success() || failure()) && ${{ github.event.inputs.disable-cleanup-job }} != 'true'
+    runs-on: ubuntu-22.04
+    env:
+      DROPLET_ID: ${{ needs.prepare-droplet.outputs.DROPLET_ID }}
+      DROPLET_IP: ${{ needs.prepare-droplet.outputs.DROPLET_IP }}
+      BLOCK_STORAGE_VOLUME_ID: ${{ needs.prepare-droplet.outputs.BLOCK_STORAGE_VOLUME_ID }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Configure SSH
+        uses: ./.github/actions/configure-ssh
+        with:
+          ssh-private-key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
+
+      - name: Install doctl
+        uses: digitalocean/action-doctl@v2
+        with:
+          token: ${{ secrets.DIGITAL_OCEAN_PERSONAL_ACCESS_TOKEN }}
+
+      - name: Unmount Block Storage file system volume
+        if: always()
         run: |
-          doctl compute droplet delete -f ${{ env.DROPLET_ID}}
+          doctl compute ssh ${{ env.DROPLET_ID}} --ssh-key-path ${{ runner.temp }}/id_rsa --ssh-command "set -e; umount /mnt/${{ vars.BLOCK_STORAGE_VOLUME_NAME }} || true"
+
+      - name: Disconnect the Block Storage volume from the Droplet       
+        if: always()
+        run: |
+          doctl compute volume-action detach ${{ env.BLOCK_STORAGE_VOLUME_ID }} ${{ env.DROPLET_ID}} --wait || true
+
+      - name: Destroy the Droplet
+        if: always()
+        run: |
+          doctl compute droplet delete -f ${{ env.DROPLET_ID}} || true
